import type { ActivityWindow, CheckpointSnapshot, InternalSession, ModelingSessionRecord, SessionRecord } from './types'
export const MODELING_SESSION_EXPORT_FIELDS = ['session_id','participant_id','start_time','task_type','intended_duration_minutes','initial_task_site','task_site_count','duration_seconds','click_count','scroll_count','keyboard_activity_count','idle_seconds','active_seconds','away_seconds','tab_switch_count','video_playing_seconds','post_session_answer','drift_label'] as const satisfies readonly (keyof ModelingSessionRecord)[]
export const SESSION_EXPORT_FIELDS = ['sessionId','protocolVersion','anonymousUserId','studyStage','condition','taskType','intendedDurationMinutes','taskSites','initialTaskSite','startTime','endTime','durationSeconds','clickCount','scrollCount','keyboardActivityCount','idleSeconds','activeSeconds','awaySeconds','tabFocusLossCount','tabSwitchCount','videoPlayingSeconds','reflectionRequestedAt','reflectionAction','postSessionAnswer','driftLabel','status','labelSource','createdAt','updatedAt'] as const satisfies readonly (keyof SessionRecord)[]
export const ACTIVITY_EXPORT_FIELDS = ['windowId','sessionId','anonymousUserId','timestamp','timestampOffsetSeconds','windowDurationSeconds','clicksInWindow','scrollEventsInWindow','keyboardActivityInWindow','idleInWindow','tabFocused','videoPlaying','taskSiteHostname'] as const satisfies readonly (keyof ActivityWindow)[]
export const CHECKPOINT_EXPORT_FIELDS = ['sessionId','anonymousUserId','cutoffSeconds','capturedAt','observable','clickCount','scrollCount','keyboardActivityCount','idleSeconds','activeSeconds','awaySeconds','tabSwitchCount','videoPlayingSeconds'] as const satisfies readonly (keyof CheckpointSnapshot)[]
export function sanitizeSession(session: InternalSession): SessionRecord { return Object.fromEntries(SESSION_EXPORT_FIELDS.map((field) => [field, session[field]])) as unknown as SessionRecord }
export function sanitizeModelingSession(session: InternalSession): ModelingSessionRecord { return { session_id: session.sessionId, participant_id: session.anonymousUserId, start_time: session.startTime, task_type: session.taskType, intended_duration_minutes: session.intendedDurationMinutes, initial_task_site: session.initialTaskSite, task_site_count: session.taskSites.length, duration_seconds: session.durationSeconds, click_count: session.clickCount, scroll_count: session.scrollCount, keyboard_activity_count: session.keyboardActivityCount, idle_seconds: session.idleSeconds, active_seconds: session.activeSeconds, away_seconds: session.awaySeconds, tab_switch_count: session.tabSwitchCount, video_playing_seconds: session.videoPlayingSeconds, post_session_answer: session.postSessionAnswer, drift_label: session.driftLabel } }
export function sanitizeActivityWindow(window: ActivityWindow): ActivityWindow { return Object.fromEntries(ACTIVITY_EXPORT_FIELDS.map((field) => [field, window[field]])) as unknown as ActivityWindow }
const PROHIBITED_FIELD_PATTERN = /(url_path|full_url|page_title|page_text|password|message|screenshot|source_code|key_value|keystroke_value|destination|browsing_history|free_text|webcam|face|emotion)/i
export function assertPrivacySafeRecord(record: Record<string, unknown>): void { const unsafeField = Object.keys(record).find((field) => PROHIBITED_FIELD_PATTERN.test(field)); if (unsafeField) throw new Error(`Export blocked by privacy guard: ${unsafeField}`) }
